// flow-typed signature: 285ab3098bb7f62e4bacfa2e67b13d47
// flow-typed version: <<STUB>>/canvas_v^1.3.5/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'canvas'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'canvas' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'canvas/lib/bindings' {
  declare module.exports: any;
}

declare module 'canvas/lib/canvas' {
  declare module.exports: any;
}

declare module 'canvas/lib/context2d' {
  declare module.exports: any;
}

declare module 'canvas/lib/image' {
  declare module.exports: any;
}

declare module 'canvas/lib/jpegstream' {
  declare module.exports: any;
}

declare module 'canvas/lib/parse-font' {
  declare module.exports: any;
}

declare module 'canvas/lib/pdfstream' {
  declare module.exports: any;
}

declare module 'canvas/lib/pngstream' {
  declare module.exports: any;
}

// Filename aliases
declare module 'canvas/index' {
  declare module.exports: $Exports<'canvas'>;
}
declare module 'canvas/index.js' {
  declare module.exports: $Exports<'canvas'>;
}
declare module 'canvas/lib/bindings.js' {
  declare module.exports: $Exports<'canvas/lib/bindings'>;
}
declare module 'canvas/lib/canvas.js' {
  declare module.exports: $Exports<'canvas/lib/canvas'>;
}
declare module 'canvas/lib/context2d.js' {
  declare module.exports: $Exports<'canvas/lib/context2d'>;
}
declare module 'canvas/lib/image.js' {
  declare module.exports: $Exports<'canvas/lib/image'>;
}
declare module 'canvas/lib/jpegstream.js' {
  declare module.exports: $Exports<'canvas/lib/jpegstream'>;
}
declare module 'canvas/lib/parse-font.js' {
  declare module.exports: $Exports<'canvas/lib/parse-font'>;
}
declare module 'canvas/lib/pdfstream.js' {
  declare module.exports: $Exports<'canvas/lib/pdfstream'>;
}
declare module 'canvas/lib/pngstream.js' {
  declare module.exports: $Exports<'canvas/lib/pngstream'>;
}
