// flow-typed signature: 8377e5b2cb81ad0696e79b20a5604bd4
// flow-typed version: <<STUB>>/paper_v0.11.5/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'paper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'paper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'paper/dist/docs/assets/js/codemirror' {
  declare module.exports: any;
}

declare module 'paper/dist/docs/assets/js/docs' {
  declare module.exports: any;
}

declare module 'paper/dist/docs/assets/js/jquery' {
  declare module.exports: any;
}

declare module 'paper/dist/docs/assets/js/paper' {
  declare module.exports: any;
}

declare module 'paper/dist/node/canvas' {
  declare module.exports: any;
}

declare module 'paper/dist/node/extend' {
  declare module.exports: any;
}

declare module 'paper/dist/node/self' {
  declare module.exports: any;
}

declare module 'paper/dist/node/xml' {
  declare module.exports: any;
}

declare module 'paper/dist/paper-core' {
  declare module.exports: any;
}

declare module 'paper/dist/paper-core.min' {
  declare module.exports: any;
}

declare module 'paper/dist/paper-full' {
  declare module.exports: any;
}

declare module 'paper/dist/paper-full.min' {
  declare module.exports: any;
}

declare module 'paper/examples/Node' {
  declare module.exports: any;
}

declare module 'paper/examples/Node.js/AnimatedStar' {
  declare module.exports: any;
}

declare module 'paper/examples/Node.js/BooleanOperations' {
  declare module.exports: any;
}

declare module 'paper/examples/Node.js/JSONtoPDF' {
  declare module.exports: any;
}

declare module 'paper/examples/Node.js/Raster' {
  declare module.exports: any;
}

declare module 'paper/examples/Node.js/RasterRemote' {
  declare module.exports: any;
}

declare module 'paper/examples/Node.js/SvgExport' {
  declare module.exports: any;
}

declare module 'paper/examples/Node.js/SvgImport' {
  declare module.exports: any;
}

declare module 'paper/examples/Node.js/Tadpoles' {
  declare module.exports: any;
}

declare module 'paper/examples/Worker/Worker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'paper/dist/docs/assets/js/codemirror.js' {
  declare module.exports: $Exports<'paper/dist/docs/assets/js/codemirror'>;
}
declare module 'paper/dist/docs/assets/js/docs.js' {
  declare module.exports: $Exports<'paper/dist/docs/assets/js/docs'>;
}
declare module 'paper/dist/docs/assets/js/jquery.js' {
  declare module.exports: $Exports<'paper/dist/docs/assets/js/jquery'>;
}
declare module 'paper/dist/docs/assets/js/paper.js' {
  declare module.exports: $Exports<'paper/dist/docs/assets/js/paper'>;
}
declare module 'paper/dist/node/canvas.js' {
  declare module.exports: $Exports<'paper/dist/node/canvas'>;
}
declare module 'paper/dist/node/extend.js' {
  declare module.exports: $Exports<'paper/dist/node/extend'>;
}
declare module 'paper/dist/node/self.js' {
  declare module.exports: $Exports<'paper/dist/node/self'>;
}
declare module 'paper/dist/node/xml.js' {
  declare module.exports: $Exports<'paper/dist/node/xml'>;
}
declare module 'paper/dist/paper-core.js' {
  declare module.exports: $Exports<'paper/dist/paper-core'>;
}
declare module 'paper/dist/paper-core.min.js' {
  declare module.exports: $Exports<'paper/dist/paper-core.min'>;
}
declare module 'paper/dist/paper-full.js' {
  declare module.exports: $Exports<'paper/dist/paper-full'>;
}
declare module 'paper/dist/paper-full.min.js' {
  declare module.exports: $Exports<'paper/dist/paper-full.min'>;
}
declare module 'paper/examples/Node.js' {
  declare module.exports: $Exports<'paper/examples/Node'>;
}
declare module 'paper/examples/Node.js/AnimatedStar.js' {
  declare module.exports: $Exports<'paper/examples/Node.js/AnimatedStar'>;
}
declare module 'paper/examples/Node.js/BooleanOperations.js' {
  declare module.exports: $Exports<'paper/examples/Node.js/BooleanOperations'>;
}
declare module 'paper/examples/Node.js/JSONtoPDF.js' {
  declare module.exports: $Exports<'paper/examples/Node.js/JSONtoPDF'>;
}
declare module 'paper/examples/Node.js/Raster.js' {
  declare module.exports: $Exports<'paper/examples/Node.js/Raster'>;
}
declare module 'paper/examples/Node.js/RasterRemote.js' {
  declare module.exports: $Exports<'paper/examples/Node.js/RasterRemote'>;
}
declare module 'paper/examples/Node.js/SvgExport.js' {
  declare module.exports: $Exports<'paper/examples/Node.js/SvgExport'>;
}
declare module 'paper/examples/Node.js/SvgImport.js' {
  declare module.exports: $Exports<'paper/examples/Node.js/SvgImport'>;
}
declare module 'paper/examples/Node.js/Tadpoles.js' {
  declare module.exports: $Exports<'paper/examples/Node.js/Tadpoles'>;
}
declare module 'paper/examples/Worker/Worker.js' {
  declare module.exports: $Exports<'paper/examples/Worker/Worker'>;
}
