// flow-typed signature: b72c904a640f7dde7703eeec6b45f8c3
// flow-typed version: <<STUB>>/scheduler_v^0.10.0/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'scheduler'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'scheduler' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'scheduler/cjs/scheduler-tracing.development' {
  declare module.exports: any;
}

declare module 'scheduler/cjs/scheduler-tracing.production.min' {
  declare module.exports: any;
}

declare module 'scheduler/cjs/scheduler-tracing.profiling.min' {
  declare module.exports: any;
}

declare module 'scheduler/cjs/scheduler.development' {
  declare module.exports: any;
}

declare module 'scheduler/cjs/scheduler.production.min' {
  declare module.exports: any;
}

declare module 'scheduler/tracing-profiling' {
  declare module.exports: any;
}

declare module 'scheduler/tracing' {
  declare module.exports: any;
}

declare module 'scheduler/umd/scheduler-tracing.development' {
  declare module.exports: any;
}

declare module 'scheduler/umd/scheduler-tracing.production.min' {
  declare module.exports: any;
}

declare module 'scheduler/umd/scheduler-tracing.profiling.min' {
  declare module.exports: any;
}

declare module 'scheduler/umd/scheduler.development' {
  declare module.exports: any;
}

declare module 'scheduler/umd/scheduler.production.min' {
  declare module.exports: any;
}

declare module 'scheduler/umd/scheduler.profiling.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'scheduler/cjs/scheduler-tracing.development.js' {
  declare module.exports: $Exports<'scheduler/cjs/scheduler-tracing.development'>;
}
declare module 'scheduler/cjs/scheduler-tracing.production.min.js' {
  declare module.exports: $Exports<'scheduler/cjs/scheduler-tracing.production.min'>;
}
declare module 'scheduler/cjs/scheduler-tracing.profiling.min.js' {
  declare module.exports: $Exports<'scheduler/cjs/scheduler-tracing.profiling.min'>;
}
declare module 'scheduler/cjs/scheduler.development.js' {
  declare module.exports: $Exports<'scheduler/cjs/scheduler.development'>;
}
declare module 'scheduler/cjs/scheduler.production.min.js' {
  declare module.exports: $Exports<'scheduler/cjs/scheduler.production.min'>;
}
declare module 'scheduler/index' {
  declare module.exports: $Exports<'scheduler'>;
}
declare module 'scheduler/index.js' {
  declare module.exports: $Exports<'scheduler'>;
}
declare module 'scheduler/tracing-profiling.js' {
  declare module.exports: $Exports<'scheduler/tracing-profiling'>;
}
declare module 'scheduler/tracing.js' {
  declare module.exports: $Exports<'scheduler/tracing'>;
}
declare module 'scheduler/umd/scheduler-tracing.development.js' {
  declare module.exports: $Exports<'scheduler/umd/scheduler-tracing.development'>;
}
declare module 'scheduler/umd/scheduler-tracing.production.min.js' {
  declare module.exports: $Exports<'scheduler/umd/scheduler-tracing.production.min'>;
}
declare module 'scheduler/umd/scheduler-tracing.profiling.min.js' {
  declare module.exports: $Exports<'scheduler/umd/scheduler-tracing.profiling.min'>;
}
declare module 'scheduler/umd/scheduler.development.js' {
  declare module.exports: $Exports<'scheduler/umd/scheduler.development'>;
}
declare module 'scheduler/umd/scheduler.production.min.js' {
  declare module.exports: $Exports<'scheduler/umd/scheduler.production.min'>;
}
declare module 'scheduler/umd/scheduler.profiling.min.js' {
  declare module.exports: $Exports<'scheduler/umd/scheduler.profiling.min'>;
}
